import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";
const statuses=["nuevo","revisado","cotizado","aprobado","en_proceso","en_espera","terminado","cerrado","cancelado"];
const priorities=["baja","media","alta","urgente"];
export default function AdminIncidentPanel({condominioId,units}){
 const [items,setItems]=useState([]),[unit,setUnit]=useState(""),[status,setStatus]=useState(""),[selected,setSelected]=useState(null),[message,setMessage]=useState(""),[visibility,setVisibility]=useState("resident"),[assignees,setAssignees]=useState([]),[canEdit,setCanEdit]=useState(false),[error,setError]=useState("");
 const call=async payload=>{const {data:{session}}=await supabase.auth.getSession();return fetch("/api/condominios/incidents",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token||""}`},body:JSON.stringify(payload)}).then(r=>r.json());};
 const load=async()=>{const r=await call({action:"list",condominioId});if(!r.ok){setError("No fue posible cargar las incidencias.");return}const nextItems=r.incidents||[];setItems(nextItems);setSelected(current=>current?nextItems.find(item=>item.id===current.id)||null:current);setCanEdit(r.capabilities?.canEdit===true);if(r.capabilities?.canEdit){const a=await call({action:"assignees",condominioId});if(a.ok)setAssignees(a.assignees||[]);}}; useEffect(()=>{load()},[condominioId]);
 const filtered=useMemo(()=>items.filter(i=>(!unit||i.unidad_id===unit)&&(!status||i.status===status)),[items,unit,status]);
 const update=async next=>{if(!canEdit)return;setError("");const r=await call({action:"update",ticketId:selected.id,condominioId,status:next||null,priority:selected.priority,responsibleProfileId:selected.responsible_profile_id||null,message,visibility,resolutionSummary:["terminado","cerrado"].includes(next)?message:null});if(r.ok){setMessage("");await load();setSelected({...selected,...r.incident});}else setError("No fue posible guardar los cambios. Verifica tus permisos y la selección.");};
 return <div>{error?<p role="alert" style={{color:"#b91c1c"}}>{error}</p>:null}<div style={{display:"flex",gap:8,marginBottom:12}}><select value={unit} onChange={e=>setUnit(e.target.value)}><option value="">Todas las unidades</option>{units.map(u=><option key={u.id} value={u.id}>{u.numero}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos los estados</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>
 <div style={{display:"grid",gridTemplateColumns:"minmax(260px,1fr) minmax(300px,1.4fr)",gap:14}}><section>{filtered.map(i=><button key={i.id} onClick={()=>setSelected(i)} style={{display:"block",width:"100%",textAlign:"left",background:"#fff",border:"1px solid #e5e7eb",borderRadius:10,padding:12,marginBottom:8}}><strong>{units.find(u=>u.id===i.unidad_id)?.numero||"Unidad"} · {i.title}</strong><br/><small>{i.status} · {i.priority}</small></button>)}</section>
 {selected?<section style={{background:"#fff",borderRadius:12,padding:16}}><h3>{selected.title}</h3><p>{selected.description}</p><label>Estado</label><select disabled={!canEdit} value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value})} style={{display:"block",margin:"6px 0 12px"}}>{statuses.map(s=><option key={s}>{s}</option>)}</select><label>Prioridad</label><select disabled={!canEdit} value={selected.priority||"media"} onChange={e=>setSelected({...selected,priority:e.target.value})} style={{display:"block",margin:"6px 0 12px"}}>{priorities.map(p=><option key={p} value={p}>{p}</option>)}</select><label>Responsable</label><select disabled={!canEdit} value={selected.responsible_profile_id||""} onChange={e=>setSelected({...selected,responsible_profile_id:e.target.value||null})} style={{display:"block",margin:"6px 0 12px"}}><option value="">Sin responsable</option>{assignees.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><textarea disabled={!canEdit} placeholder="Respuesta o nota" value={message} onChange={e=>setMessage(e.target.value)} rows={4} style={{width:"100%"}}/><select disabled={!canEdit} value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="resident">Visible al residente</option><option value="internal">Nota interna</option></select><button disabled={!canEdit} onClick={()=>update(selected.status)} style={{display:"block",marginTop:10}}>Guardar seguimiento</button><h4>Timeline</h4>{(selected.maintenance_ticket_updates||[]).map(u=><p key={u.id}><small>{u.visibility==="internal"?"Interna":"Residente"}</small><br/>{u.body||`${u.from_status||"—"} → ${u.to_status}`}</p>)}</section>:<section>Selecciona una incidencia.</section>}</div></div>
}
