import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";
const statuses=["nuevo","revisado","cotizado","aprobado","en_proceso","en_espera","terminado","cerrado","cancelado"];
export default function AdminIncidentPanel({condominioId,units}){
 const [items,setItems]=useState([]),[unit,setUnit]=useState(""),[status,setStatus]=useState(""),[selected,setSelected]=useState(null),[message,setMessage]=useState(""),[visibility,setVisibility]=useState("resident");
 const call=async payload=>{const {data:{session}}=await supabase.auth.getSession();return fetch("/api/condominios/incidents",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token||""}`},body:JSON.stringify(payload)}).then(r=>r.json());};
 const load=async()=>{const r=await call({action:"list",condominioId});setItems(r.ok?r.incidents:[])}; useEffect(()=>{load()},[condominioId]);
 const filtered=useMemo(()=>items.filter(i=>(!unit||i.unidad_id===unit)&&(!status||i.status===status)),[items,unit,status]);
 const update=async next=>{const r=await call({action:"update",ticketId:selected.id,condominioId,status:next||null,message,visibility,resolutionSummary:["terminado","cerrado"].includes(next)?message:null});if(r.ok){setMessage("");await load();setSelected({...selected,...r.incident});}};
 return <div><div style={{display:"flex",gap:8,marginBottom:12}}><select value={unit} onChange={e=>setUnit(e.target.value)}><option value="">Todas las unidades</option>{units.map(u=><option key={u.id} value={u.id}>{u.numero}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos los estados</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>
 <div style={{display:"grid",gridTemplateColumns:"minmax(260px,1fr) minmax(300px,1.4fr)",gap:14}}><section>{filtered.map(i=><button key={i.id} onClick={()=>setSelected(i)} style={{display:"block",width:"100%",textAlign:"left",background:"#fff",border:"1px solid #e5e7eb",borderRadius:10,padding:12,marginBottom:8}}><strong>{units.find(u=>u.id===i.unidad_id)?.numero||"Unidad"} · {i.title}</strong><br/><small>{i.status} · {i.priority}</small></button>)}</section>
 {selected?<section style={{background:"#fff",borderRadius:12,padding:16}}><h3>{selected.title}</h3><p>{selected.description}</p><label>Estado</label><select value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value})} style={{display:"block",margin:"6px 0 12px"}}>{statuses.map(s=><option key={s}>{s}</option>)}</select><textarea placeholder="Respuesta o nota" value={message} onChange={e=>setMessage(e.target.value)} rows={4} style={{width:"100%"}}/><select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="resident">Visible al residente</option><option value="internal">Nota interna</option></select><button onClick={()=>update(selected.status)} style={{display:"block",marginTop:10}}>Guardar seguimiento</button><h4>Timeline</h4>{(selected.maintenance_ticket_updates||[]).map(u=><p key={u.id}><small>{u.visibility==="internal"?"Interna":"Residente"}</small><br/>{u.body||`${u.from_status||"—"} → ${u.to_status}`}</p>)}</section>:<section>Selecciona una incidencia.</section>}</div></div>
}
