export const SHADOW_SYNTHETIC_FIXTURES = [
  ["p0-01", "Te mando el comprobante de la renta de agosto.", { area: "administracion", service: "rentas" }],
  ["p0-02", "Sigue saliendo agua debajo del lavabo.", { area: "administracion", service: "mantenimiento", propertyReference: "Torre Nube 101" }],
  ["p0-03", "¿Ya le pagaron al propietario?", { area: "administracion", service: "liquidaciones" }],
  ["p0-04", "¿Cuánto tengo que pagar de agua?", { area: "administracion", service: "servicios" }],
  ["p0-05", "El técnico nunca llegó.", { area: "administracion", service: "mantenimiento" }],
  ["p0-06", "Necesito sacar las llaves de X propiedad.", { area: "administracion", service: "llaves" }],
  ["p0-07", "Quiero cancelar el contrato.", { area: "administracion", service: "contratos" }],
  ["p0-08", "Voy a pagar menos este mes porque hubo una fuga.", { area: "administracion", service: "rentas" }],
  ["p0-09", "Adjunto recibo de CFE.", { area: "administracion", service: "servicios" }],
  ["p0-10", "Necesito hablar con Carlos, esto ya es un problema legal.", { area: "administracion", service: "conflictos" }],
  ["p0-11", "Ya quedó resuelto el mantenimiento.", { area: "administracion", service: "mantenimiento" }],
  ["p0-12", "¿Cuándo vence mi contrato?", { area: "administracion", service: "contratos" }],
  ["p0-13", "No tengo luz.", { area: "administracion", service: "emergencias" }],
  ["p0-14", "El propietario pregunta por su depósito.", { area: "administracion", service: "propietarios" }],
  ["p0-15", "Lo de la casa sigue igual.", { area: "administracion" }],
  ["p0-16", "Adjunto la renta y el técnico nunca llegó.", { area: "administracion", service: "multintencion" }],
  ["p0-17", "Hola", {}],
  ["p0-18", "spam", { area: "ventas", salesRelevant: true }],
  ["p0-19", "El técnico solicita confirmar acceso mañana.", { area: "administracion", service: "proveedores" }],
  ["p0-20", "¿Qué pasó con las casas del propietario?", { area: "administracion", service: "propietarios", propertyReference: "MULTIPLE" }],
  ["p0-privacy", "Mi correo es persona@example.com, teléfono +52 999 123 4567 y cuenta 1234567890123456.", { area: "administracion" }],
];
